import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const InterRegular = Inter({
  variable: "--font-Inter-Regular",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Brief: Layout principal de l'application avec configuration des polices et structure HTML de base
 * @param {Object} props - Propriétés du composant
 * @param {React.ReactNode} props.children - Composants enfants à afficher dans le layout
 * @returns {JSX.Element} Structure HTML complète avec polices configurées et contenu principal
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${InterRegular.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
